#server.port=8088
#logging.level.org.springframework=DEBUG
spring:
  application:
    name: shopapp
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp
    username: root
    password: thanh123
  jpa:
    hibernate:
      ddl-auto: update



    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088

server:
  port: 8088

jwt:
  secret-key: ACJcBsybik7d+6TOfSNqq1ew5OlFgo6aMYyF7P831vHj4D/fhHGtXxzIsbzaerLm
  issuer: shopapp
  expiration: 3600
  algorithm: HS512

cloudinary:
  cloud-name: db0sdo295
  api-key: 398119751511853
  api-secret: 3wsnWPR7fGUWmueThSSR6Sc70YM






